pub mod error;
pub mod seed;
pub mod derivation;
pub mod account;
pub mod address;
pub mod identity;
pub mod storage;
pub mod nonce;
pub mod message_signing;
pub mod structured_signing;
pub mod biometric;
pub mod encryption;

pub use error::WalletError;
pub use seed::Seed;
pub use account::{UnifiedAccount, Wallet};
pub use address::Address;
pub use storage::WalletStorage;
pub use nonce::Nonce;
pub use message_signing::{AuthMessage, AuthSignature, P2PAuthSigner, AccountAuthSigner, SignatureType};
pub use structured_signing::{DomainSeparator, TypedData, AuthRequest, TransferRequest, P2PStructuredSigner, AccountStructuredSigner, StructuredSignature, StructuredSignatureType};
pub use biometric::{BiometricManager, BiometricCredential, BiometricChallenge};
pub use encryption::EncryptionManager;